@extends('layouts.app')

@section('title', 'Contact Rugby For Education | Lilongwe, Malawi')
@section('meta_description', 'Contact Rugby For Education in Lilongwe about player support, schools, partnerships, events and community programmes.')

@section('content')
@php $headerImage = $randomImage ? asset('storage/' . ($randomImage->hasWebpVariant() ? $randomImage->getWebpShortPath() : $randomImage->getShortPath())) : asset('img/carousel-1.jpg'); @endphp
<main class="content-page">
    <header class="content-hero content-hero--compact" style="--content-hero-image: url('{{ $headerImage }}');"><div class="content-hero__overlay"></div><div class="container content-hero__inner"><nav class="content-breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><i class="fa fa-chevron-right"></i><span>Contact</span></nav><span class="home-eyebrow home-eyebrow--light">We would love to hear from you</span><h1>Let’s work together.</h1><p>Have a question, partnership idea or player support enquiry? Get in touch with Rugby For Education.</p></div></header>
    <section class="content-section content-section--soft"><div class="container"><div class="contact-layout"><div class="contact-panel"><span class="home-eyebrow">Contact details</span><h2>Start a conversation</h2><p>Whether you are a family, school, club, partner or supporter, we are here to listen and help where we can.</p><div class="contact-list"><a href="https://maps.google.com/?q=Kabwabwa+Area+25+B+Lilongwe" target="_blank" rel="noopener"><i class="fa fa-map-marker-alt"></i><span><strong>Visit us</strong>Kabwabwa, Area 25 B<br>Lilongwe, Malawi</span></a><a href="tel:+265992816663"><i class="fa fa-phone-alt"></i><span><strong>Call us</strong>+265 992 816 663<br>+265 985 543 434</span></a><a href="mailto:rugbyforeducation23@gmail.com"><i class="fa fa-envelope"></i><span><strong>Email us</strong>rugbyforeducation23@gmail.com</span></a></div><a href="{{ $supportUrl ?? 'https://www.paypal.com/paypalme/Rugby4Education' }}" target="_blank" rel="noopener noreferrer" class="home-btn home-btn--primary">Support our work <i class="fa fa-arrow-right"></i></a></div><div class="contact-image">@if($randomImage)<img src="{{ asset('storage/' . ($randomImage->hasWebpVariant() ? $randomImage->getWebpShortPath() : $randomImage->getShortPath())) }}" alt="Rugby For Education community activity" loading="lazy" decoding="async">@else<div class="home-image-placeholder"><i class="fa fa-handshake"></i></div>@endif<div class="contact-image__caption"><span>Education. Opportunity. Community.</span><strong>Good things grow when we work together.</strong></div></div></div></div></section>
</main>
@endsection
