@extends('layouts.app')

@section('title', $event->title . ' | Rugby For Education Events')
@section('meta_description', Str::limit(strip_tags($event->description), 155))
@section('social_image', asset('storage/' . $event->image))
@section('schema')
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Event', 'name' => $event->title, 'description' => Str::limit(strip_tags($event->description), 155), 'image' => asset('storage/' . $event->image), 'startDate' => \Carbon\Carbon::parse($event->start_date)->toAtomString(), 'endDate' => $event->end_date ? \Carbon\Carbon::parse($event->end_date)->toAtomString() : null, 'location' => ['@type' => 'Place', 'name' => $event->location, 'address' => ['@type' => 'PostalAddress', 'addressLocality' => 'Lilongwe', 'addressCountry' => 'MW']], 'organizer' => ['@type' => 'Organization', 'name' => 'Rugby For Education', 'url' => url('/')]], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
@endsection

@section('content')
<main class="detail-page"><div class="container"><nav class="content-breadcrumb detail-page__breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><i class="fa fa-chevron-right"></i><a href="{{ route('events') }}">Events</a><i class="fa fa-chevron-right"></i><span>{{ $event->title }}</span></nav><div class="detail-layout"><article class="detail-article"><span class="home-eyebrow">Upcoming activity</span><h1>{{ $event->title }}</h1><x-responsive-image path="{{ $event->image }}" alt="{{ $event->title }}" class="detail-article__image" sizes="(max-width: 991px) 100vw, 70vw" /><div class="detail-facts"><div><i class="fa fa-calendar-alt"></i><span><small>Date</small>{{ \Carbon\Carbon::parse($event->start_date)->format('d M Y') }}@if($event->end_date) – {{ \Carbon\Carbon::parse($event->end_date)->format('d M Y') }}@endif</span></div><div><i class="fa fa-map-marker-alt"></i><span><small>Location</small>{{ $event->location }}</span></div></div><div class="detail-article__content">{!! $event->description !!}</div><a href="{{ route('events') }}" class="home-text-link"><i class="fa fa-arrow-left"></i> Back to all events</a></article><aside class="detail-aside"><div class="detail-aside__card"><span class="home-eyebrow">Keep exploring</span><h2>More events</h2>@forelse($otherEvents as $otherEvent)<a class="detail-related" href="{{ route('events.show', $otherEvent->id) }}"><img src="{{ asset('storage/'. $otherEvent->image) }}" alt="{{ $otherEvent->title }}" loading="lazy" decoding="async"><span><small>{{ \Carbon\Carbon::parse($otherEvent->start_date)->format('d M Y') }}</small><strong>{{ $otherEvent->title }}</strong></span></a>@empty<p>No other events yet.</p>@endforelse</div><div class="detail-aside__cta"><i class="fa fa-calendar-check"></i><h2>Bring someone along.</h2><p>Share this activity with your team, school or community.</p><a href="{{ route('contact') }}">Get in touch <i class="fa fa-arrow-right"></i></a></div></aside></div></div></main>
@endsection
