@extends('layouts.app')

@section('title', $story->title . ' | Rugby For Education')
@section('meta_description', Str::limit(strip_tags($story->description), 155))
@section('social_image', asset('storage/' . $story->image))
@section('schema')
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'Article', 'headline' => $story->title, 'description' => Str::limit(strip_tags($story->description), 155), 'image' => asset('storage/' . $story->image), 'datePublished' => optional($story->created_at)->toAtomString(), 'dateModified' => optional($story->updated_at)->toAtomString(), 'author' => ['@type' => 'Organization', 'name' => 'Rugby For Education'], 'publisher' => ['@type' => 'Organization', 'name' => 'Rugby For Education', 'logo' => ['@type' => 'ImageObject', 'url' => asset('img/logo.jpg')]]], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
@endsection

@section('content')
<main class="detail-page"><div class="container"><nav class="content-breadcrumb detail-page__breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><i class="fa fa-chevron-right"></i><a href="{{ route('stories') }}">Stories</a><i class="fa fa-chevron-right"></i><span>{{ $story->title }}</span></nav><div class="detail-layout"><article class="detail-article"><span class="home-eyebrow">{{ $story->name }}</span><h1>{{ $story->title }}</h1><x-responsive-image path="{{ $story->image }}" alt="{{ $story->title }}" class="detail-article__image" sizes="(max-width: 991px) 100vw, 70vw" loading="eager" /><div class="detail-article__content">{!! $story->description !!}</div>@if($story->url_link && filter_var($story->url_link, FILTER_VALIDATE_URL))<a href="{{ $story->url_link }}" target="_blank" rel="noopener" class="home-btn home-btn--primary"><i class="fa fa-play"></i> Watch the story</a>@endif</article><aside class="detail-aside"><div class="detail-aside__card"><span class="home-eyebrow">Keep exploring</span><h2>More stories</h2>@forelse($otherStories as $otherStory)<a class="detail-related" href="{{ route('stories.show', $otherStory->id) }}"><x-responsive-image path="{{ $otherStory->image }}" alt="{{ $otherStory->title }}" sizes="90px" /><span><small>{{ $otherStory->name }}</small><strong>{{ $otherStory->title }}</strong></span></a>@empty<p>No other stories yet.</p>@endforelse</div><div class="detail-aside__cta"><i class="fa fa-heart"></i><h2>Help create the next story.</h2><p>Your support helps young players stay in school and keep moving forward.</p><a href="{{ route('support') }}">Support our work <i class="fa fa-arrow-right"></i></a></div></aside></div></div></main>
@endsection
