@extends('layouts.app')

@section('title', 'Support Rugby For Education | Donate in Malawi')
@section('meta_description', 'Support Rugby For Education and help talented young rugby players in Malawi stay in school and reach their potential.')

@section('content')
@php $paypalUrl = $supportUrl ?? 'https://www.paypal.com/paypalme/Rugby4Education'; @endphp
<main class="support-page">
    <header class="content-hero content-hero--compact support-hero"><div class="content-hero__overlay"></div><div class="container content-hero__inner"><nav class="content-breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><i class="fa fa-chevron-right"></i><span>Support Us</span></nav><span class="home-eyebrow home-eyebrow--light">Be part of the change</span><h1>Give a young player room to grow.</h1><p>Your support connects talented young people with education, rugby development and the confidence to build a brighter future.</p></div></header>
    <section class="support-give-section"><div class="container"><div class="support-give-card"><div><span class="home-eyebrow home-eyebrow--light">Give through PayPal</span><h2>Choose an amount that feels right.</h2><p>There is no contribution too small. Your donation goes toward the practical support that helps young players stay engaged in education and sport.</p></div><div class="support-give-card__action"><i class="fab fa-paypal"></i><strong>Ready to help?</strong><span>You will be taken securely to our PayPal page to complete your donation.</span><a href="{{ $paypalUrl }}" target="_blank" rel="noopener noreferrer" class="home-btn home-btn--white">Donate with PayPal <i class="fa fa-arrow-right"></i></a></div></div></div></section>
    <section class="content-section support-newsletter-section"><div class="container"><div class="support-newsletter"><div><span class="home-eyebrow">Stay close to the work</span><h2>Get updates from our community.</h2><p>Join our newsletter for player stories, event news and ways to support the next generation.</p></div>@if(session('newsletter_success'))<p class="newsletter-form__success">{{ session('newsletter_success') }}</p>@endif<form action="{{ route('newsletter.subscribe') }}" method="POST" class="support-newsletter__form">@csrf<input type="hidden" name="source" value="support-page"><input type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true" class="newsletter-form__honeypot"><label for="support-newsletter-name">Name <span>(optional)</span></label><input id="support-newsletter-name" type="text" name="name" autocomplete="name" maxlength="100"><label for="support-newsletter-email">Email address</label><input id="support-newsletter-email" type="email" name="email" autocomplete="email" required maxlength="255">@error('email')<small class="newsletter-form__error">{{ $message }}</small>@enderror<button type="submit" class="home-btn home-btn--primary">Join the newsletter <i class="fa fa-arrow-right"></i></button></form></div></div></section>
</main>
@endsection
